-- Keymaps
local builtin = require("telescope.builtin")
vim.keymap.set('n', '<leader>o', ':update<CR> :source<CR>')
vim.keymap.set('n', '<leader>sr', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>st', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>se', ":lua vim.diagnostic.open_float() <CR>", { desc = 'toggles local troubleshoot' })
vim.keymap.set('n', '<leader>ff', vim.lsp.buf.format)
vim.keymap.set('n', 'gd', vim.lsp.buf.definition, { noremap = true, silent = true })
vim.keymap.set('n', '<C-n>', ':Oil<CR>')
vim.keymap.set('n', '<leader>x', ":RunByFiletype<CR>")
